# Generated by Django 4.1 on 2022-09-01 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='participants',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
        migrations.DeleteModel(
            name='Participation',
        ),
    ]
